site_name: ServiceBot Documentation
theme:
  name: 'material'
  custom_dir: 'theme'
extra:
  logo: "images/logo-white-square.png"
  social:
    - type: github-alt
      link: https://github.com/service-bot/servicebot-docs
    - type: twitter
      link: https://twitter.com/servicebot_io
theme_dir: 'theme'
pages:
  - Introduction: index.md
  - Embeddables
    - Checkout: checkout-embed.md
    - Pricing: pricing-embed.md
    - Billing Settings: billing-settings-embed.md
    - Login: login-embed.md
    - Seat Management: seat-management-embed.md
  - Webhooks: webhooks.md
  - Developers:
    - Installation: install.md
#     - Embed Service in Existing Site: embed.md
#     - Creating a plugin: plugin.md
#     - Customization: customization.md
#     - Application Structure: structure.md
 # - Roadmap: roadmap.md
 # - Release notes: release-notes.md
#   - License: license.md
copyright: 'Copyright &copy; 2018 ServiceBot'
repo_name: service-bot/servicebot-docs
repo_url: https://github.com/service-bot/servicebot-docs
markdown_extensions:
  - admonition
