site_name: ServiceBot Documentation
theme: 'material'
extra:
  logo: "images/logo-white-square.png"
  social:
    - type: github-alt
      link: https://github.com/service-bot
    - type: twitter
      link: https://twitter.com/servicebot_io
theme_dir: 'theme'
pages:
  - Introduction: index.md
  - Getting Started: getting_started.md
  - Reference Guide: reference_guide.md
  - Installation: install.md
  - Usage:
    - For Users: user_usage.md
    - For Administrators: administration_usage.md
  - Developers:
    - Customization: customization.md
    - Contributing: contributing.md
    - Creating a plugin: plugin.md
  - Roadmap: roadmap.md
  - Release notes: release-notes.md
  - License: license.md
copyright: 'Copyright &copy; 2017 ServiceBot'
repo_name: service-bot/servicebot-docs
repo_url: https://github.com/service-bot/servicebot-docs
